### ISSUE TITLE
 Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec

### ISSUE THREAD

**Issue by rdchavan** [mojohaus/exec-maven-plugin#109]
[INFO] metron-api ......................................... SUCCESS [ 34.566 s]
[INFO] metron-management .................................. SUCCESS [ 11.149 s]
[INFO] elasticsearch-shaded ............................... SUCCESS [  9.099 s]
[INFO] metron-elasticsearch ............................... SUCCESS [01:36 min]
[INFO] metron-deployment .................................. SUCCESS [  0.020 s]
[INFO] metron-debs ........................................ FAILURE [ 11.225 s]
[INFO] metron-contrib ..................................... SKIPPED
[INFO] metron-docker ...................................... SKIPPED
[INFO] metron-performance ................................. SKIPPED
[INFO] metron-interface ................................... SKIPPED
[INFO] metron-config ...................................... SKIPPED
[INFO] metron-alerts ...................................... SKIPPED
[INFO] metron-rest-client ................................. SKIPPED
[INFO] metron-rest ........................................ SKIPPED
[INFO] site-book .......................................... SKIPPED
[INFO] 3rd party Functions (just for tests) ............... SKIPPED
[INFO] stellar-zeppelin ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:25 min
[INFO] Finished at: 2018-07-25T17:36:33+05:30
[INFO] Final Memory: 162M/398M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (docker-build) on project metron-debs: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (docker-build) on project metron-debs: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:302)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :metron-debs

**Comment by sscoltock** [comment]
Not sure if I had the same issue. You didn't include the command you ran or any details of what you were trying to achieve.

During a Metron build, as part of `vagrant provision` in the centos dir, I had something that looks similar. After a bit of digging I found the issue was a result of the command

`mvn package -DskipTests -Pbuild-debs -T 2C`

running this command in the `metron/metron-deployment` dir produced the error

`Got permission denied while trying to connect to the Docker daemon socket at...`

this was fixed by executing the following

`sudo usermod -a -G docker $USER`

after a restart (logging out and back in is probably sufficient) the build moved past this point.

**Comment by rfscholte** [comment]
This issue is incomplete, it does not contain a reproducible testproject. In the end it is the executed commandline that failed, exec-maven-plugin is just showing that result and works as expected.

**Comment by Rebek73** [comment]
I tried and it didn't work :(

**Comment by phantom03150** [comment]
did you make it.i had the same pro
