### ISSUE TITLE
error=13, Permission denied when using binary dependencies

### ISSUE THREAD

**Issue by kwin** [mojohaus/exec-maven-plugin#190]
When uploading and afterwards downloading a dependency from a remote Maven repository the file permissions (which includes the executable flag) are not kept.
That leads to the fact that when using binary dependencies as documented in <https://www.mojohaus.org/exec-maven-plugin/examples/example-exec-using-executabledependency.html> you might run into the following error

```
[ERROR] Command execution failed.
java.io.IOException: Cannot run program ".../.m2/repository/.../mybinary" (in directory "..."): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:982)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:929)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:457)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
```

I think it would be reasonable for the plugin to try to set the executable flag on the binary dependency in https://github.com/mojohaus/exec-maven-plugin/blob/d0e13ba1ddd383bc461f0efe547c91166ad789bf/src/main/java/org/codehaus/mojo/exec/ExecMojo.java#L339.

Are there other alternatives for setting the executable flag (i.e. executing `chmod +x` first on that file via `maven-exec-plugin` comes to my mind, but that feels unnecessarily complex...)?

**Comment by kwin** [comment]
I think the PR at https://github.com/mojohaus/exec-maven-plugin/pull/110 tried to solve this issue. Unfortunately it seems stale...

**Comment by kwin** [comment]
For now a reasonable workaround is to use https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html to  use binaries within archives (which keeps the flags) and copy it to some temporary directory and then use `maven-exec-plugin` to execute it from there.

**Comment by kwin** [comment]
@slachiewicz How and in which version is this fixed? The linked PR was closed without being merged…

**Comment by slachiewicz** [comment]
Looks like stale issue and you proposed workaround. If you have other solution please open PR.

**Comment by kwin** [comment]
Please close as “won’t fix” then, not as “completed”: https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

**Comment by SecondEdition** [comment]
Came across the same issue today. Configuration option to set executable bit during exec goal would be pretty slick.
