### ISSUE TITLE
Execution of Windows executables broken in 1.5.0

### ISSUE THREAD

**Issue by fjakop** [mojohaus/exec-maven-plugin#42]
I'm using exec-maven-plugin on Windows to run `npm install` in a JS project. 
```
<groupId>org.codehaus.mojo</groupId>
<artifactId>exec-maven-plugin</artifactId>
<version>1.4.0</version>
<executions>
	<execution>
		<id>npm install</id>
		<phase>generate-resources</phase>
		<goals>
			<goal>exec</goal>
		</goals>
		<configuration>
			<executable>npm</executable>
			<commandlineArgs>install --registry ${npm.registry}</commandlineArgs>
		</configuration>
	</execution>
</executions>
```

which works fine with 1.4.0 but switching to 1.5.0 results in
```
[INFO] --- exec-maven-plugin:1.5.0:exec (npm install) @ util ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "C:\Program Files\nodejs\npm" (in directory "D:\Workspaces\git-repositories\myproject"): CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 30 more
```

**Comment by khmarbaise** [comment]
Are you running on win32 based system (Windows XP or 32 Bit version of Windows 7 ?)

**Comment by fjakop** [comment]
My environment is
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: D:\Programme\Java\apache-maven-3.3.3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: D:\Programme\Java\java-8.0.40-win64-jdk\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by khmarbaise** [comment]
Have you seen the error message:

```
CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung
```

**Comment by fjakop** [comment]
Yes I did, but calling the same from cmd promt works well and with version 1.5.0 also.

**Comment by khmarbaise** [comment]
So with version 1.5.0 it works without any issue?

**Comment by fjakop** [comment]
Sorry typo, with 1.4.0 all is good, just switching version to 1.5.0 makes things break.

**Comment by gabor-farkas** [comment]
Changing "npm" to "npm.cmd" solved the issue for me

**Comment by fjakop** [comment]
We use the same POM in Windows and Linux, if I changed this, it would not run under Linux anymore.

**Comment by 1inuxoid** [comment]
I guess the easiest way is to remove npm file (shell script) on Windows, so that it will find npm.cmd.
Makes no sense to have a Windows-specific command line in pom.xml.

**Comment by fjakop** [comment]
That may be, but it does not clarify, why it worked in 1.4.0...

**Comment by gabor-farkas** [comment]
@fjakop true, I forgot about that, I'll also need this to run on jenkins and peer developers machines.

**Comment by mkarg** [comment]
The proposed fix works only on Windows, but will break Linux as it enforces the existence of file extensions, and the existence of the variable PATHEXT. Please correct it: Don't remove the top fast-success case, but make it conditional for non-Windows instead.

**Comment by hohwille** [comment]
Could you set a milestone (1.6.0?) or label so people can understand why this is closed?

**Comment by Prophet32j** [comment]
when is 1.6.0 getting added to Maven central?

**Comment by amwebexpert** [comment]
See this which solve the problem through profiles: http://stackoverflow.com/a/39407412/704681

**Comment by d0x7** [comment]
I know this is really old, but: The SO answer says it's fixed, but it doesn't seem to be. If I rename remove the npm file so that there is only npm.cmd left, it works with `<executable>` set to npm. But if it exists, it breaks (with `'C:\Program' is not recognized as an internal or external command, operable program or batch file.`). Setting npm.cmd as the command is not an option for me. Profile would work, but I'd rather get this fixed really this time, than having another workaround.

So, is this a new or different bug or am I missing something?

**Comment by mkarg** [comment]
@d0x7 I cannot reproduce your problem. I have set up a complete example from scratch on Windows 11 (64 Bit) and it worked for me out of the box using a fake `npm.cmd` batch file which simply prints all given paramters to STDOUT:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>eu.headcrashing</groupId>
    <artifactId>exec-42</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <npm.registry>C:\foo\bar</npm.registry>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>npm install</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npm</executable>
                            <commandlineArgs>install --registry ${npm.registry}</commandlineArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
``` 
```cmd
mvn package
...
[INFO] --- exec-maven-plugin:3.1.0:exec (npm install) @ exec-42 ---
install --registry C:\foo\bar
```
This works as shown above without any other changes or tricks if `npm.cmd` lives in the current working directory or if it is found on the Windows search path `PATH`. It also should work perfectly using totally different / arbitrary locations of `npm.cmd` as once as you specify that path [using a toolchain](https://www.mojohaus.org/exec-maven-plugin/examples/example-exec-using-toolchains.html).

I am sorry that it does not work for you, but apparently there seems to be something different in your case, so please tell us what that difference is.
