### ISSUE TITLE
java.lang.reflect.InvocationTargetException running exec:java

### ISSUE THREAD

**Issue by hanoii** [mojohaus/exec-maven-plugin#56]
I am a bit new to all of this but I can't seem to run something rather simple.

I am getting:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javax/enterprise/inject/UnsatisfiedResolutionException
	at ar.uba.fi.fallas.App.main(App.java:29)
	... 6 more
Caused by: java.lang.ClassNotFoundException: javax.enterprise.inject.UnsatisfiedResolutionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

But everything should be there and properly configured. It builds fine. Any pointer?

I am using Weld, CDI an drools. 

Pretty much followed all of https://salaboy.com/2015/10/20/back-to-the-basics-getting-started-with-drools-6-3-0-final with latest versions.

**Comment by khmarbaise** [comment]
You missed things on the classpath or as dependencies to run exec-maven-plugin see:

javax/enterprise/inject/UnsatisfiedResolutionException
    at ar.uba.fi.fallas.App.main(App.java:29)

**Comment by hanoii** [comment]
@khmarbaise I couldn't understand why that was happening though, because I understood that maven took care of everything.

It turned out that the issue was some kind of dependencies issues or wrongly used classes within the maven repository, removing everything and starting from scratch sorted it.
