### ISSUE TITLE
Getting error that "Can not store value into array when use mvn exec:java" in case using of the java9 modules

### ISSUE THREAD

**Issue by hakdogan** [mojohaus/exec-maven-plugin#83]
My pom.xml

```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <source>9</source>
                    <target>9</target>
                    <showWarnings>true</showWarnings>
                    <showDeprecation>true</showDeprecation>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>--module-path</argument>
                        <modulepath/>
                        <argument>--module</argument>
                        <argument>info/com.kodcu.info.InfoUser</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
</build>
```
When I run the following command getting the error

`mvn exec:java -e -X`

> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project java9-module-system: Unable to parse configuration of mojo org.codehaus.mojo:exec-maven-plugin:1.6.0:java for parameter arguments: Cannot store value into array
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.codehaus.mojo:exec-maven-plugin:1.6.0:java for parameter arguments: Cannot store value into array
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:662)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:594)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot store value into array
        at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:80)
        at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:273)
        at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:210)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
        at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:632)
        ... 23 more
Caused by: java.lang.ArrayStoreException
        at java.base/java.lang.System.arraycopy(Native Method)
        at java.base/java.util.ArrayList.toArray(ArrayList.java:413)
        at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:68)
        ... 28 more

**Comment by trcdutt** [comment]
Try using 
mvn exec:exec instead of using exec:java

**Comment by hakdogan** [comment]
Hi @trcdutt,

In this case, I'm getting this exception
> I/O Error: target/modulepath (No such file or directory)

**Comment by trcdutt** [comment]
Your configuration section in the POM.xml for exec maven section should be similar to below:

 				<configuration>
					<executable>java</executable>
 					<arguments>
						<argument>--module-path</argument>
						<modulepath/>
						<argument>--module</argument>
						<argument>mainmodule/com.trc.mainmodule.App</argument>
					</arguments> 
				</configuration> 
mainmodule -- is the module name given in the module-info.java file
com.main.trc.mainmodule.App is the startup class

**Comment by hakdogan** [comment]
Hi @trcdutt,

Your code snippet is like as my snippet, I didn't see a difference. 

The "info" is my main modue name, I give this name in the module-info.java file. Also InfoUser class is my startup class. You can look at my [repository](https://github.com/hakdogan/Java9-module-system-with-maven). The plugin is not currently in the POM file.

**Comment by trcdutt** [comment]
It looks like your maven plugin is not upto date.
Use this below:
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				**<version>**3.7.0**</version>**
				<configuration>
					<source>9</source>
					<target>9</target>
					<showWarnings>true</showWarnings>
					<showDeprecation>true</showDeprecation>
				</configuration>
			</plugin>

**Comment by trcdutt** [comment]
I am using compiler plugin 3.7.0 instead of 3.6.1 in the info project. Also when you execute, go to info project and execute mvn exec:exec. I was able to run your project.

**Comment by trcdutt** [comment]
C:\Workspaces\java-9-workspace\Java9-module-system-with-maven-master\Java9ModuleSystem\info>mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building info 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (default-cli) @ info ---
[INFO ] 2018-01-27 12:26:46.148 [main] InfoUser - User{firstName='Huseyin', lastName='Akdogan', profession='Expert Software Consultant', age=41}
[INFO ] 2018-01-27 12:26:46.157 [main] ConnDB - ConnDB instance being returned.
[INFO ] 2018-01-27 12:26:46.483 [main] ConnDB - H2 Database inserted through Statement
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.553 s
[INFO] Finished at: 2018-01-27T12:26:46-07:00
[INFO] Final Memory: 8M/27M
[INFO] ------------------------------------------------------------------------

**Comment by hakdogan** [comment]
Hi @trcdutt,

Thank you so much.

You showed me my mistake.

I had run the command in **Java9ModuleSystem** directory every time.  When I run the command in info directory, result is success even with the plugin version 3.6.2

👍
