### ISSUE TITLE
[Enhancement] Support for JPMS module path for exec:java

### ISSUE THREAD

**Issue by mkarg** [mojohaus/exec-maven-plugin#90]
Currently there is only support for an automatic module path with `exec:exec`. There also is support for automatic class path with `exec:java`. But there is no support for module path with `exec:java`. :-(

**It would be great to also have support for automatic module path with `exec:java`!**

**Comment by rfscholte** [comment]
[simple-exec.zip](https://github.com/mojohaus/exec-maven-plugin/files/2853122/simple-exec.zip)
A simplified way of how exec-maven-plugin and ModuleLayer should work (now it fails...)

**Comment by rfscholte** [comment]
[simple-exec2.zip](https://github.com/mojohaus/exec-maven-plugin/files/2871804/simple-exec2.zip)

```
java -jar simple-exec-0.0.1-SNAPSHOT.jar
unnamed module @35fb3008
Exception in thread "com.greetings.Main.main()" java.lang.IllegalAccessException: symbolic reference class is not accessible: class com.greetings.Main, from public Lookup
        at java.base/java.lang.invoke.MemberName.makeAccessException(Unknown Source)
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(Unknown Source)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(Unknown Source)
        at nl.sourcegrounds.jpms.ClassMain$MainRunner.run(ClassMain.java:29)
        at java.base/java.lang.Thread.run(Unknown Source)
```
